# standard jekyll configuration

permalink: /:year/:month/:day/:title/
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: rdiscount

# configuration required for some pages

domain: jeu.arthion.fr
title: Games.corner
author: Kamiben
email: eadel@arthion.fr

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
