# standard jekyll configuration

permalink: /:year/:month/:day/:title/
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: rdiscount

# configuration required for some pages

domain: domain.com
title: Blog Title
author: Name
email: email

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
